name = "VenComic"

type = "javascript"

[build]
command = "npm run build"
[build.upload]
format = "modules"
dir = ".next"
pages_build_output_dir = ".next"

[env.production]
workers_dev = false
compatibility_date = "2025-04-09"
