name = "v1-dig"
main = "functions/api/[[path]].js"
compatibility_date = "2023-10-30"

[build]
command = "npm run build:cloudflare"

[site]
bucket = ".next"

# Cấu hình cho Cloudflare Pages
pages_build_output_dir = ".next"
