name = "v1-dig"
main = "functions/_worker.js"
compatibility_date = "2024-04-09"

[build]
command = "npm run build:cloudflare"

[site]
bucket = ".next-cf"

# Cấu hình cho Cloudflare Pages
pages_build_output_dir = ".next-cf"
