[build]
command = "npm run build:cloudflare"
output_directory = ".next"

[site]
bucket = ".next"

[build.upload]
format = "directory"

[env.production]
routes = [
  { pattern = "/api/*", script = "functions/api/[[path]].js" },
  { pattern = "/*", serve = "/.next" }
]
