name = "v1-dig"
main = "functions/_worker.js"
compatibility_date = "2024-04-09"

[triggers]
crons = []

[build]
command = "npm run build"

# Bỏ qua cấu hình site
# [site]
# bucket = ".next-cf"
# # Thêm exclude patterns để bỏ qua thư mục cache
# exclude = [
#   "cache/**/*",
#   "**/node_modules/**",
#   "**/.git/**",
#   "**/cache/webpack/**/*.pack",
#   "**/cache/webpack/**/*.pack.gz"
# ]

[env.production]
workers_dev = true

# Cấu hình cho Cloudflare Pages - Bỏ qua vì dùng next-on-pages
# pages_build_output_dir = ".next-cf"

# Thêm bindings cho ASSETS - Bỏ qua vì dùng next-on-pages
# [[bindings]]
# name = "ASSETS"
# type = "assets"
